name: Build and deploy .NET application to container app mvcacagawithdocker-app-202309200
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: mvcacagawithdocker
  CONTAINER_APP_NAME: mvcacagawithdocker-app-202309200
  CONTAINER_APP_RESOURCE_GROUP_NAME: aapt0920LinuxGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: mvcacagawithdocker20230920074524.azurecr.io
  DOCKER_FILE_PATH: ./Dockerfile
  PROJECT_NAME_FOR_DOCKER: mvcacagawithdocker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.MvcAcaGaWithDocker20230920074524_USERNAME_DBA2 }}
        password: ${{ secrets.MvcAcaGaWithDocker20230920074524_PASSWORD_DBA2 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.mvcacagawithdocker_app_202309200_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.MvcAcaGaWithDocker20230920074524_USERNAME_DBA2 }} --password ${{ secrets.MvcAcaGaWithDocker20230920074524_PASSWORD_DBA2 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
